version: '3.8'

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: cargo-postgres
    environment:
      POSTGRES_USER: cargo_user
      POSTGRES_PASSWORD: cargo_password
      POSTGRES_DB: cargo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cargo_user -d cargo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
